<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>L14 Promise Demo 5</title>
</head>

<body>
    <script>
        //wrap an asynchronous operation in a promise
        //It's possible to chain after a failure, i.e. a catch, 
        //which is useful to accomplish new actions even after an action failed in the chain.

        let aPromise = new Promise((resolve, reject) => {
            console.log("Initial");
            resolve();
        }).then(() => {
            throw new Error("Somthing failed");
            //console.log("Do this");
        }).catch(() => {
            console.log("Error message.")
        }).then(() => {
            console.log("Do this whatever happend before");
        });

    </script>


    </script>

</body>

</html>